name: JDG

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - run: pip install -r requirements.txt
      - run: python -m mkdocs build --verbose

      - if: github.ref == 'refs/heads/master'
        run: python -m mkdocs gh-deploy --force
