name: Check Markdown Links

on:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/markdown_link_check.yml"
      - "mlc_config.json"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        folder-path: docs
        max-depth: 1
